use MAV_UNIVERTMP;

-- task 1
SELECT FACULTY.FACULTY_NAME, PULPIT.PULPIT_NAME, PROFESSION.PROFESSION_NAME
FROM FACULTY, PULPIT, PROFESSION
WHERE FACULTY.FACULTY = PULPIT.FACULTY and PROFESSION_NAME in (SELECT PROFESSION.PROFESSION_NAME FROM PROFESSION WHERE (PROFESSION.PROFESSION_NAME like '%технология%'));

-- task 2
SELECT FACULTY.FACULTY_NAME, PULPIT.PULPIT_NAME, PROFESSION.PROFESSION_NAME
FROM PULPIT inner join FACULTY 
ON PULPIT.FACULTY = FACULTY.FACULTY inner join PROFESSION
ON PROFESSION_NAME IN (SELECT PROFESSION.PROFESSION_NAME FROM PROFESSION WHERE (PROFESSION.PROFESSION_NAME like '%технология%'));

-- task 3
SELECT FACULTY.FACULTY_NAME, PULPIT.PULPIT_NAME, PROFESSION.PROFESSION_NAME
FROM PULPIT inner join FACULTY 
ON PULPIT.FACULTY = FACULTY.FACULTY inner join PROFESSION
ON PROFESSION.PROFESSION_NAME like '%технология%';

-- task 4
SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM.AUDITORIUM_NAME , AUDITORIUM.AUDITORIUM_CAPACITY, AUDITORIUM.AUDITORIUM_TYPE
FROM AUDITORIUM
WHERE AUDITORIUM.AUDITORIUM_CAPACITY = (SELECT TOP(1) AUDITORIUM_CAPACITY FROM AUDITORIUM ORDER BY AUDITORIUM_CAPACITY DESC);

-- task 5
SELECT DISTINCT FACULTY.FACULTY_NAME
FROM PULPIT, FACULTY
WHERE NOT EXISTS (SELECT * FROM PULPIT WHERE FACULTY.FACULTY = PULPIT.FACULTY);

-- task 6
SELECT TOP 1
	(select avg(NOTE) from PROGRESS where PROGRESS.SUBJECTS like '%БД%')[Базы данных],
	(select avg(NOTE) from PROGRESS where PROGRESS.SUBJECTS like '%ОАиП%')[ОАиП]
FROM PROGRESS;

--task 7
SELECT PROGRESS.NOTE, PROGRESS.IDSTUDENT, PROGRESS.SUBJECTS
FROM PROGRESS WHERE PROGRESS.NOTE >=all (
SELECT PROGRESS.NOTE FROM PROGRESS WHERE PROGRESS.IDSTUDENT = '1019'
);

--task 8
SELECT PROGRESS.NOTE, PROGRESS.IDSTUDENT, PROGRESS.SUBJECTS
FROM PROGRESS WHERE PROGRESS.NOTE >any (
SELECT PROGRESS.NOTE FROM PROGRESS WHERE PROGRESS.IDSTUDENT = '1019'
);